{{- $chartName := include "job-syncer.name" . -}}
{{- $tracingUrl := include "job-syncer.tracingUrl" . -}}
{{- $metricsUrl := include "job-syncer.metricsUrl" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  {{-  $ca := (include "common.ca.merged" . ) | fromYaml }}
  {{- if $ca.enabled }}
  REQUESTS_CA_BUNDLE: {{ printf "%s/%s" $ca.path $ca.key | quote }}
  NODE_EXTRA_CA_CERTS: {{ printf "%s/%s" $ca.path $ca.key | quote }}
  {{- end }}
  JOB_SYNCER_INTERVAL_MS: {{ .Values.env.intervalMS | quote }}
  CATALOG_URL: http://{{ .Release.Name }}-catalog
  LINK_NAME: {{ .Values.env.catalog.link.name | quote }}
  LINK_DESCRIPTION: {{ .Values.env.catalog.link.description | quote }}
  LINK_URL: {{ .Values.env.catalog.link.url | quote }}
  LINK_PROTOCOL: {{ .Values.env.catalog.link.protocol | quote }}
  {{- $jobManager := (include "common.jobManager.merged" . ) | fromYaml }}
  JOB_MANAGER_URL: {{ $jobManager.url | quote }}
  {{- $job := (include "common.job.merged" . ) | fromYaml }}
  JOB_TYPE: {{ $job.type | quote }}
